### ISSUE TITLE
Other Solid systems are using VCARD rather than FOAF

### ISSUE THREAD

**Issue by melvincarvalho** [solid-live/specs#8]
Currently the Group canonicalization relies on foaf Group and foaf member.  Other solid systems are using vcard Group and vcard member as pointed out by @timbl :

https://lists.w3.org/Archives/Public/public-rww/2016Oct/0019.html

and @dmitrizagidulin :

https://gitter.im/solid/chat?at=5804ed5b48292577612fbf6c

In the interests of interoperability it would make sense to change the spec and implementation to switch to vcard.

Solution would be to change : 
- [x] Spec change references to FOAF -> VCARD
- [x] Implementation change references FOAF -> VCARD
- [x] Tests change references FOAF -> VCARD
- [x] Recomupe example hash in spec

**Comment by dmitrizagidulin** [comment]
> it would make sense to change the spec

Which spec are you referring to?

**Comment by dmitrizagidulin** [comment]
Oh, wait sounds like the Solid Live spec. Never mind :)
